services:
  # MongoDB
  cadmus-minerva-mongo:
    image: mongo
    container_name: cadmus-minerva-mongo
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    command: mongod --logpath=/dev/null
    ports:
      - 127.0.0.1:27017:27017
    networks:
      - cadmus-minerva-network

  # PostgreSQL
  cadmus-minerva-pgsql:
    image: postgres
    container_name: cadmus-minerva-pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 127.0.0.1:5432:5432
    networks:
      - cadmus-minerva-network

  # Cadmus minerva API
  cadmus-minerva-api:
    image: vedph2020/cadmus-minerva-api:0.0.1
    container_name: cadmus-minerva-api
    ports:
      - 5106:8080
    depends_on:
      - cadmus-minerva-mongo
      - cadmus-minerva-pgsql
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - CONNECTIONSTRINGS__DEFAULT=mongodb://cadmus-minerva-mongo:27017/{0}
      - CONNECTIONSTRINGS__AUTH=Server=cadmus-minerva-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - CONNECTIONSTRINGS__INDEX=Server=cadmus-minerva-pgsql;port=5432;Database={0};User Id=postgres;Password=postgres;Include Error Detail=True
      - SERILOG__CONNECTIONSTRING=mongodb://cadmus-minerva-mongo:27017/{0}-log
      - STOCKUSERS__0__PASSWORD=P4ss-W0rd!
      - SEED__DELAY=20
      - MESSAGING__APIROOTURL=http://cadmusapi.azurewebsites.net
      - MESSAGING__APPROOTURL=http://cadmusapi.com/
      - MESSAGING__SUPPORTEMAIL=support@cadmus.com
    networks:
      - cadmus-minerva-network

  # Cadmus minerva App
  cadmus-app:
    image: vedph2020/cadmus-minerva-app:0.0.1
    container_name: cadmus-minerva-app
    ports:
      - 4200:80
    depends_on:
      - cadmus-minerva-api
      - cadmus-biblio-api
    networks:
      - cadmus-minerva-network

networks:
  cadmus-minerva-network:
    driver: bridge
